### ISSUE TITLE
Beautiful Fullscreen volume bug

### ISSUE THREAD

**Issue by unoriginals** [Oein/beautifulfullscreen#2]
If you enable the volume option and you go out of beautiful fullscreen mode you can still click the volume slider even though you can't see it meaning if im trying to click on my playlists on the left i will most likely not be able to as im changing the volume

**Comment by Oein** [comment]
Fixed on commit [d983a7](https://github.com/Oein/beautifulfullscreen/commit/d983a7668833f5a01337ce328bcb05f99e43f83d)
