### ISSUE TITLE
How to close the fullscreen?

### ISSUE THREAD

**Issue by JustSxm** [Oein/beautifulfullscreen#5]
Hello!

Others seemed to use Escape, but I cant seem to find how to exit from it.

**Comment by JustSxm** [comment]
I suggest to write it down in the read me or somewhere to make it easier for the user to understand

Enter: The Icon
Exit: Double Click

**Comment by Oein** [comment]
Updated on [2440d6](https://github.com/Oein/beautifulfullscreen/commit/2440d6b0f3ccd828d9a240099bc746db1c22a65b)
